-- ============================================================
-- DEMO_DB Recreation Script
-- Run this on your new Snowflake account
-- ============================================================
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

//CREATE DATABASE IF NOT EXISTS DEMO_DB;
USE DATABASE DEMO_DB;
USE SCHEMA PUBLIC;


CREATE OR REPLACE STREAMLIT DEMO_DB.PUBLIC.DRIVER_SAFETY_APP_V26
    FROM '@DEMO_DB.PUBLIC.DRIVER_SAFETY_STREAMLIT'
    MAIN_FILE = 'streamlit_app_v22.py'
    QUERY_WAREHOUSE = COMPUTE_WH;

    
-- 1. DATABASE & SCHEMA
CREATE DATABASE IF NOT EXISTS DEMO_DB;
USE DATABASE DEMO_DB;
USE SCHEMA PUBLIC;

-- ============================================================
-- 2. TABLES (create base tables first, then dependent objects)
-- ============================================================

CREATE OR REPLACE TABLE MODULE_A_FRAME_PREDICTIONS (
    SESSION_ID VARCHAR(64),
    SOURCE_TYPE VARCHAR(10),
    SOURCE_NAME VARCHAR(256),
    FRAME_ID NUMBER(38,0),
    TIMESTAMP_SECONDS FLOAT,
    A1_PROB_DROWSY FLOAT,
    A1_PROB_YAWN FLOAT,
    A1_PROB_NOD FLOAT,
    A2_PROB_EYE_CLOSED FLOAT,
    A2_EYE_OPENNESS_SCORE FLOAT,
    FRAME_RISK FLOAT,
    RISK_LEVEL VARCHAR(10),
    HEAD_PITCH FLOAT,
    MAR FLOAT,
    EAR FLOAT,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    DRIVER_ID VARCHAR(64),
    TRIP_ID VARCHAR(64),
    HEAD_YAW FLOAT,
    HEAD_ROLL FLOAT,
    LEFT_EAR FLOAT,
    RIGHT_EAR FLOAT,
    QUALITY_SCORE FLOAT,
    FACE_CONFIDENCE FLOAT,
    PREPROCESS_METHOD VARCHAR(32),
    FATIGUE_SIGNAL_CONFIDENCE FLOAT,
    UNCERTAIN_FRAME BOOLEAN,
    REVIEW_FLAG VARCHAR(32),
    EYE_CLOSED_BINARY NUMBER(38,0),
    BLINK_BINARY NUMBER(38,0),
    PERCLOS_30S FLOAT,
    BLINK_RATE_PER_MIN FLOAT,
    LIGHTING_METHOD VARCHAR(32),
    A1_CONFIDENCE FLOAT,
    A2_CONFIDENCE FLOAT,
    A1_DROWSY_FLAG NUMBER(38,0),
    MAR_YUNET FLOAT,
    MAR_FOR_YAWN FLOAT,
    MOE FLOAT,
    HPR VARCHAR(256),
    GAZE_PITCH_RAW FLOAT,
    GAZE_YAW_RAW FLOAT,
    YAWN_PROB_HIPPOYD FLOAT,
    LANDMARK3D_OK BOOLEAN,
    BRIGHTNESS_SCORE FLOAT,
    BLUR_SCORE FLOAT,
    INFERENCE_MODE VARCHAR(32),
    CREATED_AT_CLIENT VARCHAR(64)
);

CREATE OR REPLACE TABLE MODULE_A_EVENTS (
    SESSION_ID VARCHAR(64),
    EVENT_TYPE VARCHAR(64),
    EVENT_START_TIME FLOAT,
    EVENT_END_TIME FLOAT,
    DURATION FLOAT,
    SEVERITY VARCHAR(16),
    EXPLANATION VARCHAR(1024),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EVENT_ID VARCHAR(64),
    DRIVER_ID VARCHAR(64),
    TRIP_ID VARCHAR(64),
    EVENT_START_TS FLOAT,
    EVENT_END_TS FLOAT,
    DURATION_SECONDS FLOAT,
    SEVERITY_SCORE FLOAT,
    CONFIDENCE FLOAT,
    DOMINANT_ZONE VARCHAR(32),
    RISK_GROUP VARCHAR(32),
    ALERT_SENT BOOLEAN,
    ALERT_TYPE VARCHAR(64),
    EVENT_CONFIRMATION_STATUS VARCHAR(32)
);

CREATE OR REPLACE TABLE MODULE_A_SESSION_SUMMARY (
    SESSION_ID VARCHAR(64),
    SOURCE_NAME VARCHAR(256),
    SOURCE_TYPE VARCHAR(10),
    TOTAL_FRAMES_PROCESSED NUMBER(38,0),
    TOTAL_DURATION_SECONDS FLOAT,
    AVG_A1_PROB_DROWSY FLOAT,
    MAX_A1_PROB_DROWSY FLOAT,
    AVG_A2_PROB_EYE_CLOSED FLOAT,
    EYE_CLOSURE_BURDEN FLOAT,
    PROLONGED_CLOSURE_COUNT NUMBER(38,0),
    YAWN_SUPPORT_SCORE FLOAT,
    NOD_SUPPORT_SCORE FLOAT,
    TOTAL_HIGH_RISK_DURATION FLOAT,
    TOTAL_CAUTION_DURATION FLOAT,
    FINAL_SESSION_RISK VARCHAR(10),
    SUMMARY_TEXT VARCHAR(2048),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    DRIVER_ID VARCHAR(64),
    TRIP_ID VARCHAR(64),
    SESSION_START_TS VARCHAR(64),
    SESSION_END_TS VARCHAR(64),
    DURATION_SECONDS FLOAT,
    PERCLOS FLOAT,
    BLINK_COUNT NUMBER(38,0),
    BLINK_FREQ_PER_MIN FLOAT,
    AVG_BLINK_DURATION_SECONDS FLOAT,
    AVG_EAR FLOAT,
    MEAN_CONFIDENCE FLOAT,
    UNCERTAIN_RATIO FLOAT,
    POOR_QUALITY_SESSION BOOLEAN,
    MODEL_VERSION_A1 VARCHAR(128),
    MODEL_VERSION_A2 VARCHAR(128),
    APP_VERSION VARCHAR(64)
);

CREATE OR REPLACE TABLE MODULE_B_FRAME_PREDICTIONS (
    SESSION_ID VARCHAR(64),
    INPUT_TYPE VARCHAR(10),
    SOURCE_FILE_NAME VARCHAR(256),
    FRAME_INDEX NUMBER(38,0),
    TIMESTAMP_SECONDS FLOAT,
    ZONE_PRED VARCHAR(32),
    RISK_GROUP_PRED VARCHAR(16),
    OFFROAD_PROB FLOAT,
    OFFROAD_PRED NUMBER(38,0),
    CONFIDENCE FLOAT,
    ENTROPY FLOAT,
    ZONE_PROB_FORWARD FLOAT,
    ZONE_PROB_LAP FLOAT,
    ZONE_PROB_LEFT_MIRROR FLOAT,
    ZONE_PROB_RADIO FLOAT,
    ZONE_PROB_REARVIEW FLOAT,
    ZONE_PROB_RIGHT_MIRROR FLOAT,
    ZONE_PROB_SHOULDER FLOAT,
    ZONE_PROB_SPEEDOMETER FLOAT,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    DRIVER_ID VARCHAR(64),
    TRIP_ID VARCHAR(64),
    MARGIN FLOAT,
    UNCERTAINTY_SCORE FLOAT,
    ATTN_UNCERTAIN BOOLEAN,
    REVIEW_FLAG VARCHAR(32),
    INFERENCE_MODE VARCHAR(32),
    ATTN_LABEL VARCHAR(32),
    GAZE_SOURCE VARCHAR(32),
    CALIB_PCT FLOAT,
    YAW_CORRECTED FLOAT,
    PITCH_CORRECTED FLOAT,
    ZONE_TOP2 VARCHAR(128),
    B_ENSEMBLE_SIZE NUMBER(38,0),
    CREATED_AT_CLIENT VARCHAR(64)
);

CREATE OR REPLACE TABLE MODULE_B_EVENTS (
    SESSION_ID VARCHAR(64),
    EVENT_TYPE VARCHAR(64),
    EVENT_START_TIME FLOAT,
    EVENT_END_TIME FLOAT,
    DURATION FLOAT,
    DOMINANT_ZONE VARCHAR(32),
    DOMINANT_RISK_GROUP VARCHAR(16),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EVENT_ID VARCHAR(64),
    DRIVER_ID VARCHAR(64),
    TRIP_ID VARCHAR(64),
    EVENT_START_TS FLOAT,
    EVENT_END_TS FLOAT,
    DURATION_SECONDS FLOAT,
    SEVERITY VARCHAR(16),
    SEVERITY_SCORE FLOAT,
    CONFIDENCE FLOAT,
    RISK_GROUP VARCHAR(32),
    ALERT_SENT BOOLEAN,
    ALERT_TYPE VARCHAR(64),
    EVENT_CONFIRMATION_STATUS VARCHAR(32)
);

CREATE OR REPLACE TABLE MODULE_B_SESSION_SUMMARY (
    SESSION_ID VARCHAR(64),
    SOURCE_FILE_NAME VARCHAR(256),
    TOTAL_FRAMES NUMBER(38,0),
    TOTAL_DURATION_SECONDS FLOAT,
    OFFROAD_RATIO FLOAT,
    MAX_OFFROAD_STREAK_SECONDS FLOAT,
    OFFROAD_EVENTS_PER_MIN FLOAT,
    HIGHRISK_RATIO FLOAT,
    MAX_HIGHRISK_STREAK_SECONDS FLOAT,
    HIGHRISK_EVENTS_PER_MIN FLOAT,
    MIRROR_GLANCE_FREQUENCY_PER_MIN FLOAT,
    AVG_MIRROR_GLANCE_DURATION_SECONDS FLOAT,
    SAFE_FORWARD_RATIO FLOAT,
    MEAN_CONFIDENCE FLOAT,
    MEAN_ENTROPY FLOAT,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    DRIVER_ID VARCHAR(64),
    TRIP_ID VARCHAR(64),
    SESSION_START_TS VARCHAR(64),
    SESSION_END_TS VARCHAR(64),
    DURATION_SECONDS FLOAT,
    UNCERTAIN_RATIO FLOAT,
    POOR_QUALITY_SESSION BOOLEAN,
    REPEATED_DISTRACTION_EVENTS NUMBER(38,0),
    MODEL_VERSION_B VARCHAR(128),
    APP_VERSION VARCHAR(64)
);

CREATE OR REPLACE TABLE REALTIME_ALERTS (
    ALERT_ID VARCHAR(64),
    SESSION_ID VARCHAR(64),
    DRIVER_ID VARCHAR(64),
    TRIP_ID VARCHAR(64),
    ALERT_TIMESTAMP_SECONDS FLOAT,
    ALERT_WALL_TIME VARCHAR(64),
    ALERT_TYPE VARCHAR(64),
    SEVERITY VARCHAR(16),
    SEVERITY_SCORE FLOAT,
    ESCALATION_LEVEL NUMBER(38,0),
    FATIGUE_SCORE FLOAT,
    OFFROAD_PROB FLOAT,
    ZONE_AT_ALERT VARCHAR(32),
    CONFIDENCE FLOAT,
    MESSAGE VARCHAR(512),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CREATED_AT_CLIENT VARCHAR(64),
    LIGHTING_AT_ALERT VARCHAR(32)
);

CREATE OR REPLACE TABLE UNIFIED_DRIVER_SESSION_SUMMARY (
    SESSION_ID VARCHAR(64),
    DRIVER_ID VARCHAR(64),
    TRIP_ID VARCHAR(64),
    SESSION_START_TS VARCHAR(64),
    SESSION_END_TS VARCHAR(64),
    DURATION_SECONDS FLOAT,
    SOURCE_FILE_NAME VARCHAR(256),
    MODEL_VERSION_A1 VARCHAR(128),
    MODEL_VERSION_A2 VARCHAR(128),
    MODEL_VERSION_B VARCHAR(128),
    APP_VERSION VARCHAR(64),
    FATIGUE_SCORE FLOAT,
    DISTRACTION_SCORE FLOAT,
    COMBINED_DRIVER_SAFETY_SCORE FLOAT,
    DRIVER_RATING VARCHAR(8),
    SUMMARY_TEXT VARCHAR(4096),
    ESCALATION_LEVEL NUMBER(38,0),
    TRIP_START_TS VARCHAR(64),
    TRIP_END_TS VARCHAR(64),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    MEAN_MODEL_CONFIDENCE FLOAT,
    TOTAL_REALTIME_ALERTS NUMBER(38,0)
);

CREATE OR REPLACE TABLE DRIVER_SCORECARDS (
    DRIVER_ID VARCHAR(64),
    TRIP_ID VARCHAR(64),
    SESSION_ID VARCHAR(64),
    FATIGUE_RISK_SCORE FLOAT,
    DISTRACTION_RISK_SCORE FLOAT,
    COMBINED_DRIVER_SAFETY_SCORE FLOAT,
    AVERAGE_OFFROAD_RATIO FLOAT,
    PROLONGED_EYE_CLOSURE_COUNT NUMBER(38,0),
    MIRROR_USAGE_PATTERN VARCHAR(64),
    SAFE_FORWARD_RATIO FLOAT,
    HIGHRISK_EVENTS_PER_DRIVING_HOUR FLOAT,
    DRIVER_RATING VARCHAR(8),
    CREATED_AT_CLIENT VARCHAR(64),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DRIVER_TIMELINE (
    SESSION_ID VARCHAR(64),
    DRIVER_ID VARCHAR(64),
    TRIP_ID VARCHAR(64),
    TIMELINE_STATE VARCHAR(64),
    START_TS FLOAT,
    END_TS FLOAT,
    DURATION_SECONDS FLOAT,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CREATED_AT_CLIENT TIMESTAMP_NTZ(9)
);

CREATE OR REPLACE TABLE DRIVER_RECOVERY_EVENTS (
    RECOVERY_ID VARCHAR(64),
    SESSION_ID VARCHAR(64),
    DRIVER_ID VARCHAR(64),
    TRIP_ID VARCHAR(64),
    RECOVERY_TIMESTAMP_SECONDS FLOAT,
    PEAK_ESCALATION_BEFORE NUMBER(38,0),
    RECOVERY_DURATION_SECONDS FLOAT,
    PREVIOUS_STATE VARCHAR(64),
    ALERT_COUNT_BEFORE NUMBER(38,0),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CREATED_AT_CLIENT VARCHAR(64)
);

CREATE OR REPLACE TABLE DRIVER_FATIGUE_TIMELINE (
    SESSION_ID VARCHAR(16777216),
    DRIVER_ID VARCHAR(16777216),
    TRIP_ID VARCHAR(16777216),
    WINDOW_START_TS FLOAT,
    WINDOW_END_TS FLOAT,
    AVG_PERCLOS FLOAT,
    BLINK_RATE FLOAT,
    EYE_CLOSURE_EVENTS NUMBER(38,0),
    YAWN_EVENTS NUMBER(38,0),
    FATIGUE_RISK_BUCKET VARCHAR(16777216),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DRIVER_FATIGUE_WINDOWS (
    WINDOW_ID VARCHAR(16777216),
    SESSION_ID VARCHAR(16777216),
    DRIVER_ID VARCHAR(16777216),
    TRIP_ID VARCHAR(16777216),
    WINDOW_START_TS FLOAT,
    WINDOW_END_TS FLOAT,
    AVG_PERCLOS FLOAT,
    BLINK_RATE FLOAT,
    EYE_CLOSURE_COUNT NUMBER(38,0),
    YAWN_COUNT NUMBER(38,0),
    AVG_A2 FLOAT,
    AVG_DROWSY FLOAT,
    FATIGUE_BUCKET VARCHAR(16777216),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DRIVER_GAZE_WINDOWS (
    WINDOW_ID VARCHAR(16777216),
    SESSION_ID VARCHAR(16777216),
    DRIVER_ID VARCHAR(16777216),
    TRIP_ID VARCHAR(16777216),
    WINDOW_START_TS FLOAT,
    WINDOW_END_TS FLOAT,
    FORWARD_SECONDS FLOAT,
    MIRROR_SECONDS FLOAT,
    OFFROAD_SECONDS FLOAT,
    MIRROR_GLANCE_COUNT NUMBER(38,0),
    REARVIEW_GLANCE_COUNT NUMBER(38,0),
    MAX_OFFROAD_STREAK FLOAT,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE EVIDENCE_CLIP_INDEX (
    CLIP_ID VARCHAR(64),
    SESSION_ID VARCHAR(64),
    DRIVER_ID VARCHAR(64),
    TRIP_ID VARCHAR(64),
    ALERT_ID VARCHAR(64),
    ALERT_TYPE VARCHAR(64),
    SEVERITY VARCHAR(16),
    EVENT_TIMESTAMP_SECONDS FLOAT,
    CLIP_START_TS FLOAT,
    CLIP_END_TS FLOAT,
    DURATION_SECONDS FLOAT,
    STAGE_PATH VARCHAR(512),
    FILE_SIZE_BYTES NUMBER(38,0),
    CREATED_AT_CLIENT VARCHAR(64),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- 3. STAGES
-- ============================================================

CREATE OR REPLACE STAGE DRIVER_EVIDENCE_CLIPS
    COMMENT = 'Short MP4 clips cut around high/critical driver safety alerts'
    DIRECTORY = (ENABLE = TRUE);

CREATE OR REPLACE STAGE DRIVER_SAFETY_MODELS
    DIRECTORY = (ENABLE = TRUE);

CREATE OR REPLACE STAGE DRIVER_SAFETY_STREAMLIT
    DIRECTORY = (ENABLE = TRUE);

CREATE OR REPLACE STAGE VIDEO_FILE_STAGE
    DIRECTORY = (ENABLE = TRUE);

-- ============================================================
-- 4. VIEWS (depend on base tables)
-- ============================================================

CREATE OR REPLACE VIEW DRIVER_ALERT_PROFILE AS
SELECT
    DRIVER_ID,
    ALERT_TYPE,
    COUNT(*) AS TOTAL_OCCURRENCES,
    AVG(SEVERITY_SCORE) AS AVG_SEVERITY,
    MAX(SEVERITY_SCORE) AS MAX_SEVERITY,
    COUNT(DISTINCT SESSION_ID) AS SESSIONS_WITH_THIS_ALERT
FROM DEMO_DB.PUBLIC.REALTIME_ALERTS
WHERE DRIVER_ID IS NOT NULL
GROUP BY DRIVER_ID, ALERT_TYPE;

CREATE OR REPLACE VIEW DRIVER_DAILY_TREND AS
SELECT
    DRIVER_ID,
    DATE_TRUNC('day', TO_TIMESTAMP(SESSION_START_TS)) AS DAY,
    AVG(COMBINED_DRIVER_SAFETY_SCORE) AS AVG_SCORE,
    SUM(TOTAL_REALTIME_ALERTS) AS DAILY_ALERTS,
    COUNT(DISTINCT SESSION_ID) AS TRIPS,
    AVG(FATIGUE_SCORE) AS AVG_FATIGUE_SCORE,
    AVG(DISTRACTION_SCORE) AS AVG_DISTRACTION_SCORE,
    SUM(DURATION_SECONDS) AS TOTAL_DRIVING_SECONDS,
    MAX(ESCALATION_LEVEL) AS MAX_ESCALATION
FROM DEMO_DB.PUBLIC.UNIFIED_DRIVER_SESSION_SUMMARY
WHERE SESSION_START_TS IS NOT NULL
GROUP BY DRIVER_ID, DAY;

CREATE OR REPLACE VIEW DRIVER_HOURLY_FATIGUE AS
SELECT
    DRIVER_ID,
    HOUR(TO_TIMESTAMP(SESSION_START_TS)) AS HOUR_OF_DAY,
    AVG(FATIGUE_SCORE) AS AVG_FATIGUE,
    AVG(DISTRACTION_SCORE) AS AVG_DISTRACTION,
    COUNT(DISTINCT SESSION_ID) AS SESSION_COUNT,
    SUM(TOTAL_REALTIME_ALERTS) AS TOTAL_ALERTS_THIS_HOUR
FROM DEMO_DB.PUBLIC.UNIFIED_DRIVER_SESSION_SUMMARY
WHERE SESSION_START_TS IS NOT NULL
GROUP BY DRIVER_ID, HOUR_OF_DAY;

CREATE OR REPLACE VIEW DRIVER_WEEKLY_TREND AS
SELECT
    DRIVER_ID,
    DATE_TRUNC('week', TO_TIMESTAMP(SESSION_START_TS)) AS WEEK,
    AVG(COMBINED_DRIVER_SAFETY_SCORE) AS AVG_SCORE,
    SUM(TOTAL_REALTIME_ALERTS) AS WEEKLY_ALERTS,
    COUNT(DISTINCT SESSION_ID) AS TRIPS
FROM DEMO_DB.PUBLIC.UNIFIED_DRIVER_SESSION_SUMMARY
GROUP BY 1, 2;

CREATE OR REPLACE VIEW EVIDENCE_CLIP_BROWSE AS
SELECT
    e.CLIP_ID,
    e.SESSION_ID,
    e.DRIVER_ID,
    e.TRIP_ID,
    e.ALERT_TYPE,
    e.SEVERITY,
    e.EVENT_TIMESTAMP_SECONDS,
    e.DURATION_SECONDS,
    e.STAGE_PATH,
    e.FILE_SIZE_BYTES,
    a.MESSAGE AS ALERT_MESSAGE,
    a.ESCALATION_LEVEL,
    a.ZONE_AT_ALERT,
    a.CONFIDENCE,
    e.CREATED_AT
FROM DEMO_DB.PUBLIC.EVIDENCE_CLIP_INDEX e
LEFT JOIN DEMO_DB.PUBLIC.REALTIME_ALERTS a
    ON e.ALERT_ID = a.ALERT_ID
ORDER BY e.CREATED_AT DESC;

-- ============================================================
-- 5. DYNAMIC TABLES (depend on base tables and views)
--    NOTE: Update warehouse name if different in new account
-- ============================================================

CREATE OR REPLACE DYNAMIC TABLE DRIVER_RISK_LEADERBOARD
    LAG = '1 hour'
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    DRIVER_ID,
    AVG(COMBINED_DRIVER_SAFETY_SCORE) AS AVG_SAFETY_SCORE,
    COUNT(DISTINCT SESSION_ID) AS TOTAL_SESSIONS,
    MAX(ESCALATION_LEVEL) AS PEAK_ESCALATION,
    SUM(TOTAL_REALTIME_ALERTS) AS TOTAL_ALERTS
FROM DEMO_DB.PUBLIC.UNIFIED_DRIVER_SESSION_SUMMARY
GROUP BY DRIVER_ID;

CREATE OR REPLACE DYNAMIC TABLE DRIVER_TOP_ALERT_TYPES
    LAG = '1 hour'
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    DRIVER_ID,
    ALERT_TYPE,
    TOTAL_OCCURRENCES,
    AVG_SEVERITY,
    ROW_NUMBER() OVER (PARTITION BY DRIVER_ID ORDER BY TOTAL_OCCURRENCES DESC) AS RANK
FROM DEMO_DB.PUBLIC.DRIVER_ALERT_PROFILE
QUALIFY RANK <= 3;

-- ============================================================
-- 6. VIEW that depends on DYNAMIC TABLE
-- ============================================================

CREATE OR REPLACE VIEW FLEET_RISK_HOTSPOTS AS
SELECT
    DRIVER_ID,
    AVG_SAFETY_SCORE,
    TOTAL_ALERTS,
    TOTAL_SESSIONS,
    ROUND(TOTAL_ALERTS / NULLIF(TOTAL_SESSIONS, 0), 2) AS ALERTS_PER_SESSION,
    PEAK_ESCALATION,
    CASE
        WHEN AVG_SAFETY_SCORE > 0.80 THEN 'CRITICAL - Immediate Coaching'
        WHEN AVG_SAFETY_SCORE > 0.60 THEN 'HIGH - Schedule This Week'
        WHEN AVG_SAFETY_SCORE > 0.40 THEN 'MEDIUM - Monitor Closely'
        WHEN TOTAL_ALERTS / NULLIF(TOTAL_SESSIONS, 0) > 5 THEN 'FREQUENT ALERTS - Review'
        ELSE 'NORMAL'
    END AS INTERVENTION_FLAG,
    CASE
        WHEN PEAK_ESCALATION >= 4 THEN TRUE
        ELSE FALSE
    END AS HAS_CRITICAL_INCIDENT
FROM DEMO_DB.PUBLIC.DRIVER_RISK_LEADERBOARD
WHERE AVG_SAFETY_SCORE > 0.40
   OR TOTAL_ALERTS / NULLIF(TOTAL_SESSIONS, 0) > 5
   OR PEAK_ESCALATION >= 4
ORDER BY AVG_SAFETY_SCORE DESC;
