USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE DEMO_DB;
USE SCHEMA PUBLIC;

-- =========================
-- Alter existing Module A frame table
-- =========================
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS DRIVER_ID VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS TRIP_ID VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS HEAD_YAW FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS HEAD_ROLL FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS LEFT_EAR FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS RIGHT_EAR FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS QUALITY_SCORE FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS FACE_CONFIDENCE FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS PREPROCESS_METHOD VARCHAR(32);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS FATIGUE_SIGNAL_CONFIDENCE FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS UNCERTAIN_FRAME BOOLEAN;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS REVIEW_FLAG VARCHAR(32);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS EYE_CLOSED_BINARY INT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS BLINK_BINARY INT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS PERCLOS_30S FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS BLINK_RATE_PER_MIN FLOAT;

-- =========================
-- Alter existing Module A events table
-- =========================
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_EVENTS ADD COLUMN IF NOT EXISTS EVENT_ID VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_EVENTS ADD COLUMN IF NOT EXISTS DRIVER_ID VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_EVENTS ADD COLUMN IF NOT EXISTS TRIP_ID VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_EVENTS ADD COLUMN IF NOT EXISTS EVENT_START_TS FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_EVENTS ADD COLUMN IF NOT EXISTS EVENT_END_TS FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_EVENTS ADD COLUMN IF NOT EXISTS DURATION_SECONDS FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_EVENTS ADD COLUMN IF NOT EXISTS SEVERITY_SCORE FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_EVENTS ADD COLUMN IF NOT EXISTS CONFIDENCE FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_EVENTS ADD COLUMN IF NOT EXISTS DOMINANT_ZONE VARCHAR(32);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_EVENTS ADD COLUMN IF NOT EXISTS RISK_GROUP VARCHAR(32);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_EVENTS ADD COLUMN IF NOT EXISTS ALERT_SENT BOOLEAN;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_EVENTS ADD COLUMN IF NOT EXISTS ALERT_TYPE VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_EVENTS ADD COLUMN IF NOT EXISTS EVENT_CONFIRMATION_STATUS VARCHAR(32);

-- =========================
-- Alter existing Module A session table
-- =========================
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS DRIVER_ID VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS TRIP_ID VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS SESSION_START_TS VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS SESSION_END_TS VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS DURATION_SECONDS FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS PERCLOS FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS BLINK_COUNT INT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS BLINK_FREQ_PER_MIN FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS AVG_BLINK_DURATION_SECONDS FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS AVG_EAR FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS MEAN_CONFIDENCE FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS UNCERTAIN_RATIO FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS POOR_QUALITY_SESSION BOOLEAN;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS MODEL_VERSION_A1 VARCHAR(128);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS MODEL_VERSION_A2 VARCHAR(128);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_A_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS APP_VERSION VARCHAR(64);

-- =========================
-- Alter existing Module B frame table
-- =========================
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS DRIVER_ID VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS TRIP_ID VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS MARGIN FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS UNCERTAINTY_SCORE FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS ATTN_UNCERTAIN BOOLEAN;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_FRAME_PREDICTIONS ADD COLUMN IF NOT EXISTS REVIEW_FLAG VARCHAR(32);

-- =========================
-- Alter existing Module B events table
-- =========================
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_EVENTS ADD COLUMN IF NOT EXISTS EVENT_ID VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_EVENTS ADD COLUMN IF NOT EXISTS DRIVER_ID VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_EVENTS ADD COLUMN IF NOT EXISTS TRIP_ID VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_EVENTS ADD COLUMN IF NOT EXISTS EVENT_START_TS FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_EVENTS ADD COLUMN IF NOT EXISTS EVENT_END_TS FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_EVENTS ADD COLUMN IF NOT EXISTS DURATION_SECONDS FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_EVENTS ADD COLUMN IF NOT EXISTS SEVERITY VARCHAR(16);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_EVENTS ADD COLUMN IF NOT EXISTS SEVERITY_SCORE FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_EVENTS ADD COLUMN IF NOT EXISTS CONFIDENCE FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_EVENTS ADD COLUMN IF NOT EXISTS RISK_GROUP VARCHAR(32);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_EVENTS ADD COLUMN IF NOT EXISTS ALERT_SENT BOOLEAN;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_EVENTS ADD COLUMN IF NOT EXISTS ALERT_TYPE VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_EVENTS ADD COLUMN IF NOT EXISTS EVENT_CONFIRMATION_STATUS VARCHAR(32);

-- =========================
-- Alter existing Module B session table
-- =========================
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS DRIVER_ID VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS TRIP_ID VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS SESSION_START_TS VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS SESSION_END_TS VARCHAR(64);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS DURATION_SECONDS FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS UNCERTAIN_RATIO FLOAT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS POOR_QUALITY_SESSION BOOLEAN;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS REPEATED_DISTRACTION_EVENTS INT;
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS MODEL_VERSION_B VARCHAR(128);
ALTER TABLE IF EXISTS DEMO_DB.PUBLIC.MODULE_B_SESSION_SUMMARY ADD COLUMN IF NOT EXISTS APP_VERSION VARCHAR(64);

-- =========================
-- New unified tables
-- =========================
CREATE TABLE IF NOT EXISTS DEMO_DB.PUBLIC.UNIFIED_DRIVER_SESSION_SUMMARY (
    SESSION_ID VARCHAR(64),
    DRIVER_ID VARCHAR(64),
    TRIP_ID VARCHAR(64),
    SESSION_START_TS VARCHAR(64),
    SESSION_END_TS VARCHAR(64),
    DURATION_SECONDS FLOAT,
    SOURCE_FILE_NAME VARCHAR(256),
    MODEL_VERSION_A1 VARCHAR(128),
    MODEL_VERSION_A2 VARCHAR(128),
    MODEL_VERSION_B VARCHAR(128),
    APP_VERSION VARCHAR(64),
    FATIGUE_SCORE FLOAT,
    DISTRACTION_SCORE FLOAT,
    COMBINED_DRIVER_SAFETY_SCORE FLOAT,
    DRIVER_RATING VARCHAR(8),
    SUMMARY_TEXT VARCHAR(4096),
    ESCALATION_LEVEL INT,
    TRIP_START_TS VARCHAR(64),
    TRIP_END_TS VARCHAR(64),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DEMO_DB.PUBLIC.DRIVER_SCORECARDS (
    DRIVER_ID VARCHAR(64),
    TRIP_ID VARCHAR(64),
    SESSION_ID VARCHAR(64),
    FATIGUE_RISK_SCORE FLOAT,
    DISTRACTION_RISK_SCORE FLOAT,
    COMBINED_DRIVER_SAFETY_SCORE FLOAT,
    AVERAGE_OFFROAD_RATIO FLOAT,
    PROLONGED_EYE_CLOSURE_COUNT INT,
    MIRROR_USAGE_PATTERN VARCHAR(64),
    SAFE_FORWARD_RATIO FLOAT,
    HIGHRISK_EVENTS_PER_DRIVING_HOUR FLOAT,
    DRIVER_RATING VARCHAR(8),
    CREATED_AT_CLIENT VARCHAR(64),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DEMO_DB.PUBLIC.DRIVER_TIMELINE (
    SESSION_ID VARCHAR(64),
    DRIVER_ID VARCHAR(64),
    TRIP_ID VARCHAR(64),
    TIMELINE_STATE VARCHAR(64),
    START_TS FLOAT,
    END_TS FLOAT,
    DURATION_SECONDS FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
