-- ============================================================
-- DRIVER SAFETY STREAMLIT APP - COMPLETE SETUP GUIDE
-- Run these in order from a Snowsight SQL Worksheet
-- Role: ACCOUNTADMIN | Warehouse: COMPUTE_WH
-- ============================================================

-- ─── STEP 1: Create database and schema ───
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS DEMO_DB;
USE DATABASE DEMO_DB;
USE SCHEMA PUBLIC;

-- ─── STEP 2: Create tables for Module A (Drowsiness) ───

CREATE TABLE IF NOT EXISTS DEMO_DB.PUBLIC.MODULE_A_FRAME_PREDICTIONS (
    SESSION_ID VARCHAR(64),
    SOURCE_TYPE VARCHAR(10),
    SOURCE_NAME VARCHAR(256),
    FRAME_ID INT,
    TIMESTAMP_SECONDS FLOAT,
    A1_PROB_DROWSY FLOAT,
    A1_PROB_YAWN FLOAT,
    A1_PROB_NOD FLOAT,
    A2_PROB_EYE_CLOSED FLOAT,
    A2_EYE_OPENNESS_SCORE FLOAT,
    FRAME_RISK FLOAT,
    RISK_LEVEL VARCHAR(10),
    HEAD_PITCH FLOAT,
    MAR FLOAT,
    EAR FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DEMO_DB.PUBLIC.MODULE_A_EVENTS (
    SESSION_ID VARCHAR(64),
    EVENT_TYPE VARCHAR(64),
    EVENT_START_TIME FLOAT,
    EVENT_END_TIME FLOAT,
    DURATION FLOAT,
    SEVERITY VARCHAR(16),
    EXPLANATION VARCHAR(1024),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DEMO_DB.PUBLIC.MODULE_A_SESSION_SUMMARY (
    SESSION_ID VARCHAR(64),
    SOURCE_NAME VARCHAR(256),
    SOURCE_TYPE VARCHAR(10),
    TOTAL_FRAMES_PROCESSED INT,
    TOTAL_DURATION_SECONDS FLOAT,
    AVG_A1_PROB_DROWSY FLOAT,
    MAX_A1_PROB_DROWSY FLOAT,
    AVG_A2_PROB_EYE_CLOSED FLOAT,
    EYE_CLOSURE_BURDEN FLOAT,
    PROLONGED_CLOSURE_COUNT INT,
    YAWN_SUPPORT_SCORE FLOAT,
    NOD_SUPPORT_SCORE FLOAT,
    TOTAL_HIGH_RISK_DURATION FLOAT,
    TOTAL_CAUTION_DURATION FLOAT,
    FINAL_SESSION_RISK VARCHAR(10),
    SUMMARY_TEXT VARCHAR(2048),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ─── STEP 3: Create tables for Module B (Attentiveness) ───

CREATE TABLE IF NOT EXISTS DEMO_DB.PUBLIC.MODULE_B_FRAME_PREDICTIONS (
    SESSION_ID VARCHAR(64),
    INPUT_TYPE VARCHAR(10),
    SOURCE_FILE_NAME VARCHAR(256),
    FRAME_INDEX INT,
    TIMESTAMP_SECONDS FLOAT,
    ZONE_PRED VARCHAR(32),
    RISK_GROUP_PRED VARCHAR(16),
    OFFROAD_PROB FLOAT,
    OFFROAD_PRED INT,
    CONFIDENCE FLOAT,
    ENTROPY FLOAT,
    ZONE_PROB_FORWARD FLOAT,
    ZONE_PROB_LAP FLOAT,
    ZONE_PROB_LEFT_MIRROR FLOAT,
    ZONE_PROB_RADIO FLOAT,
    ZONE_PROB_REARVIEW FLOAT,
    ZONE_PROB_RIGHT_MIRROR FLOAT,
    ZONE_PROB_SHOULDER FLOAT,
    ZONE_PROB_SPEEDOMETER FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DEMO_DB.PUBLIC.MODULE_B_EVENTS (
    SESSION_ID VARCHAR(64),
    EVENT_TYPE VARCHAR(64),
    EVENT_START_TIME FLOAT,
    EVENT_END_TIME FLOAT,
    DURATION FLOAT,
    DOMINANT_ZONE VARCHAR(32),
    DOMINANT_RISK_GROUP VARCHAR(16),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DEMO_DB.PUBLIC.MODULE_B_SESSION_SUMMARY (
    SESSION_ID VARCHAR(64),
    SOURCE_FILE_NAME VARCHAR(256),
    TOTAL_FRAMES INT,
    TOTAL_DURATION_SECONDS FLOAT,
    OFFROAD_RATIO FLOAT,
    MAX_OFFROAD_STREAK_SECONDS FLOAT,
    OFFROAD_EVENTS_PER_MIN FLOAT,
    HIGHRISK_RATIO FLOAT,
    MAX_HIGHRISK_STREAK_SECONDS FLOAT,
    HIGHRISK_EVENTS_PER_MIN FLOAT,
    MIRROR_GLANCE_FREQUENCY_PER_MIN FLOAT,
    AVG_MIRROR_GLANCE_DURATION_SECONDS FLOAT,
    SAFE_FORWARD_RATIO FLOAT,
    MEAN_CONFIDENCE FLOAT,
    MEAN_ENTROPY FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ─── STEP 4: Create stages ───

CREATE STAGE IF NOT EXISTS DEMO_DB.PUBLIC.DRIVER_SAFETY_MODELS
    DIRECTORY = (ENABLE = TRUE);

CREATE STAGE IF NOT EXISTS DEMO_DB.PUBLIC.DRIVER_SAFETY_STREAMLIT
    DIRECTORY = (ENABLE = TRUE);

-- ─── STEP 5: Upload files via Snowsight UI ───
-- After uploading all files, run STEP 6.

-- ─── STEP 6: Verify uploads ───
LIST @DEMO_DB.PUBLIC.DRIVER_SAFETY_MODELS;
LIST @DEMO_DB.PUBLIC.DRIVER_SAFETY_STREAMLIT;

-- ─── STEP 7: Create the Streamlit app ───
CREATE OR REPLACE STREAMLIT DEMO_DB.PUBLIC.DRIVER_SAFETY_APP_V3
    FROM '@DEMO_DB.PUBLIC.DRIVER_SAFETY_STREAMLIT'
    MAIN_FILE = 'streamlit_app_v3.py'
    QUERY_WAREHOUSE = COMPUTE_WH;


-- ─── STEP 8: Verify the app was created ───
SHOW STREAMLITS IN SCHEMA DEMO_DB.PUBLIC;
LIST @DEMO_DB.PUBLIC.DRIVER_SAFETY_MODELS;

-- ─── TROUBLESHOOTING ───
-- If you need to re-upload files, use OVERWRITE = TRUE in the UI
-- or drop and recreate the stage:
--   DROP STAGE DEMO_DB.PUBLIC.DRIVER_SAFETY_STREAMLIT;
--   CREATE STAGE DEMO_DB.PUBLIC.DRIVER_SAFETY_STREAMLIT DIRECTORY = (ENABLE = TRUE);
--   Then re-upload files

-- To drop and recreate the app:
--   DROP STREAMLIT DEMO_DB.PUBLIC.DRIVER_SAFETY_APP;
--   Then re-run STEP 7
